//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoptifySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdoptionPayment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdoptionPayment()
        {
            this.Adoptions = new HashSet<Adoption>();
        }
    
        public int AdoptionPaymentID { get; set; }
        public Nullable<int> Adoption_ID { get; set; }
        public Nullable<int> Animal_Type_ID { get; set; }
        public Nullable<int> Payment_Type_ID { get; set; }
        public Nullable<decimal> Adoption_Fee { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adoption> Adoptions { get; set; }
        public virtual Adoption Adoption { get; set; }
        public virtual Animal_Type Animal_Type { get; set; }
        public virtual Payment_Type Payment_Type { get; set; }
    }
}
