//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoptifySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeCheckReport
    {
        public int HomeCheckReportID { get; set; }
        public Nullable<int> HomeCheck_ID { get; set; }
        public Nullable<bool> HomeCheckStatus { get; set; }
        public string HCDoc { get; set; }
    
        public virtual HomeCheck HomeCheck { get; set; }
    }
}
